language: python
python:
#  - "3.6"
#  - "3.7"
  - "3.8"
#  - "3.9"
#  - "3.9-dev"  # 3.9 development branch
#  - "nightly"  # nightly build
# command to install dependencies
install:
  - conda env create -f environment.yml
  - pip install -e .
# command to run tests
script:
  - pytest --disable-pytest-warnings