name: rgym
channels:
  - defaults
dependencies:
  - ca-certificates=2020.7.22
  - certifi=2020.6.20
  - libedit=3.1.20191231
  - libffi=3.3
  - ncurses=6.2
  - openssl=1.1.1g
  - pip=20.2.2
  - python=3.8.5
  - readline=8.0
  - setuptools=49.6.0
  - sqlite=3.33.0
  - tk=8.6.10
  - wheel=0.35.1
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - absl-py==0.10.0
    - allennlp==1.3.0
    - allennlp-models==1.3.0
    - appnope==0.1.0
    - argon2-cffi==20.1.0
    - astunparse==1.6.3
    - attrs==20.2.0
    - backcall==0.2.0
    - bert-score==0.3.6
    - bleach==3.1.5
    - blis==0.4.1
    - boto==2.49.0
    - boto3==1.14.56
    - botocore==1.17.56
    - bpemb==0.3.2
    - cachetools==4.1.1
    - catalogue==1.0.0
    - cffi==1.14.2
    - chardet==3.0.4
    - click==7.1.2
    - cloudpickle==1.6.0
    - configparser==5.0.0
    - conllu==4.2.1
    - cycler==0.10.0
    - cymem==2.0.3
    - cytoolz==0.10.1
    - datasets==1.1.3
    - decorator==4.4.2
    - defusedxml==0.6.0
    - deprecated==1.2.10
    - dill==0.3.1.1
    - docker-pycreds==0.4.0
    - docopt==0.6.2
    - docutils==0.15.2
    - editdistance==0.5.3
    - entrypoints==0.3
    - fastbpe==0.1.0
    - filelock==3.0.12
    - flair==0.6.1.post1
    - ftfy==5.8
    - funcy==1.14
    - future==0.18.2
    - fuzzywuzzy==0.18.0
    - gast==0.3.3
    - gdown==3.12.2
    - gensim==3.8.3
    - gitdb==4.0.5
    - gitpython==3.1.8
    - google-auth==1.21.1
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.2.0
    - gql==0.2.0
    - graphql-core==1.1
    - grpcio==1.31.0
    - h5py==2.10.0
    - hyperopt==0.2.4
    - idna==2.10
    - importlib-metadata==1.7.0
    - iniconfig==1.0.1
    - ipykernel==5.3.4
    - ipython==7.18.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - janome==0.4.0
    - jedi==0.17.2
    - jinja2==2.11.2
    - jmespath==0.10.0
    - joblib==0.16.0
    - json5==0.9.5
    - jsonlines==1.2.0
    - jsonnet==0.16.0
    - jsonpatch==1.26
    - jsonpickle==1.4.1
    - jsonpointer==2.0
    - jsonschema==3.2.0
    - jupyter-client==6.1.7
    - jupyter-core==4.6.3
    - jupyterlab==2.2.6
    - jupyterlab-server==1.2.0
    - kaleido==0.1.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.2.0
    - konoha==4.6.2
    - langdetect==1.0.8
    - language-tool-python==2.4.0
    - lemminflect==0.2.1
    - lru-dict==1.1.6
    - lxml==4.5.2
    - markdown==3.2.2
    - markupsafe==1.1.1
    - matplotlib==3.3.1
    - mistune==0.8.4
    - more-itertools==8.5.0
    - mpld3==0.3
    - multiprocess==0.70.11.1
    - murmurhash==1.0.2
    - nbconvert==5.6.1
    - nbformat==5.0.7
    - networkx==2.5
    - nlp==0.4.0
    - nlpaug==1.1.1
    - nltk==3.4.4
    - notebook==6.1.3
    - num2words==0.5.10
    - numpy==1.17.4
    - nvidia-ml-py3==7.352.0
    - oauthlib==3.1.0
    - opt-einsum==3.3.0
    - overrides==3.1.0
    - packaging==20.4
    - pandas==1.0.3
    - pandocfilters==1.4.2
    - parso==0.7.1
    - pathtools==0.1.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==7.2.0
    - plac==1.1.3
    - plotly==4.9.0
    - pluggy==0.13.1
    - preshed==3.0.2
    - progressbar==2.5
    - prometheus-client==0.8.0
    - promise==2.3
    - prompt-toolkit==3.0.7
    - protobuf==3.13.0
    - psutil==5.7.2
    - ptyprocess==0.6.0
    - py==1.9.0
    - py-rouge==1.1
    - pyahocorasick==1.4.0
    - pyarrow==0.17.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.20
    - pygments==2.6.1
    - pyparsing==2.4.7
    - pyrsistent==0.16.0
    - pysocks==1.7.1
    - pytest==6.0.1
    - python-dateutil==2.8.1
    - python-levenshtein==0.12.0
    - pytorch-lightning==0.8.1
    - pytz==2020.1
    - pyyaml==5.3.1
    - pyzmq==19.0.2
    - regex==2020.7.14
    - requests==2.24.0
    - requests-oauthlib==1.3.0
    - retrying==1.3.3
    - rouge-score==0.0.4
    - rsa==4.6
    - s3transfer==0.3.3
    - sacremoses==0.0.43
    - scikit-learn==0.23.2
    - scipy==1.4.1
    - segtok==1.5.10
    - semver==2.13.0
    - send2trash==1.5.0
    - sentence-transformers==0.3.5.1
    - sentencepiece==0.1.91
    - sentry-sdk==0.17.3
    - shortuuid==1.0.1
    - six==1.15.0
    - smart-open==2.1.1
    - smmap==3.0.4
    - spacy==2.3.2
    - sqlitedict==1.7.0
    - srsly==1.0.2
    - stanza==1.1.1
    - subprocess32==3.5.4
    - tabulate==0.8.7
    - tensorboard==2.3.0
    - tensorboard-plugin-wit==1.7.0
    - tensorboardx==2.1
    - tensorflow==2.3.0
    - tensorflow-estimator==2.3.0
    - tensorflow-hub==0.9.0
    - termcolor==1.1.0
    - terminado==0.8.3
    - terminaltables==3.1.0
    - testpath==0.4.4
    - textattack==0.2.15
    - textblob==0.15.3
    - thinc==7.4.1
    - threadpoolctl==2.1.0
    - tokenizers==0.9.4
    - toml==0.10.1
    - toolz==0.10.0
    - torch==1.7.1
    - torchfile==0.1.0
    - tornado==6.0.4
    - tqdm==4.41.0
    - traitlets==5.0.3
    - transformers==4.0.1
    - typing-extensions==3.7.4.3
    - urllib3==1.25.10
    - visdom==0.1.8.9
    - wasabi==0.8.0
    - watchdog==0.10.3
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==0.57.0
    - werkzeug==1.0.1
    - widgetsnbextension==3.5.1
    - word2number==1.1
    - wrapt==1.12.1
    - xxhash==2.0.0
    - zipp==3.1.0

